spring:
  application:
    name: aggregator

logging:
  level:
    ru.yandex.practicum: TRACE
    org:
      springframework: ERROR
      apache.kafka: WARN

aggregator:
  kafka:
    producer-props:
      "bootstrap.servers": localhost:9092
      "client.id": "aggregator-client"
      "key.serializer": org.apache.kafka.common.serialization.StringSerializer
      "value.serializer": kafka.serializer.GeneralAvroSerializer
    consumer-props:
      "bootstrap.servers": localhost:9092
      "group.id": "aggregator-group"
      "key.deserializer": org.apache.kafka.common.serialization.StringDeserializer
      "value.deserializer": kafka.serializer.SensorEventDeserializer
    topics:
      sensors-events: telemetry.sensors.v1
      sensors-snapshots: telemetry.snapshots.v1
